USE [atlhoops]
GO

/****** Object:  StoredProcedure [dbo].[sendtext]    Script Date: 03/17/2013 12:31:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sendtext]

AS

BEGIN

DECLARE @BCCMAIL AS VARCHAR(70)
DECLARE @NEWSUBJECT AS VARCHAR(50)
DECLARE @NEWBODY AS VARCHAR(300)
DECLARE @RECPIENTCOUNT AS INT
DECLARE @ACTIVEROW AS INT
DECLARE @MAIL AS VARCHAR(MAX)
DECLARE @BEFOREEMAIL AS VARCHAR(MAX)
DECLARE @LASTROW3 AS INT
DECLARE @ACTIVEROW3 AS INT

SET @BCCMAIL = 'your blind copy recipient'
SET @NEWSUBJECT = 'subject line'
SET @NEWBODY = (SELECT *
			    FROM message)
SET @RECPIENTCOUNT = (SELECT COUNT(name)
				      FROM recipients)
SET @ACTIVEROW = 1

SELECT ROWNUMBER3 = ROW_NUMBER() OVER(ORDER BY ABB3.EMAIL), ABB3.EMAIL
INTO #TEXTEMAILADDRESSES
FROM 
			(SELECT EMAIL 
			 FROM cell_text_emails) AS ABB3
SET @LASTROW3 = (SELECT MAX(ROWNUMBER3) FROM #TEXTEMAILADDRESSES)
SET @ACTIVEROW3 = (SELECT MIN(ROWNUMBER3) FROM #TEXTEMAILADDRESSES)

WHILE @RECPIENTCOUNT >=  @ACTIVEROW
	BEGIN
		IF @ACTIVEROW = 1
			BEGIN
				SET @BEFOREEMAIL = (SELECT phone
							 FROM recipients
							 WHERE row_number = @ACTIVEROW)
				WHILE @LASTROW3 >= @ACTIVEROW3
					BEGIN
						IF @ACTIVEROW3 = 1
							BEGIN
								SET @MAIL = @BEFOREEMAIL + (SELECT EMAIL 
															FROM #TEXTEMAILADDRESSES
															WHERE ROWNUMBER3 = @ACTIVEROW3)
							END
						ELSE 
							BEGIN
								SET @MAIL = @MAIL + '; ' + @BEFOREEMAIL + (SELECT EMAIL 
																   FROM #TEXTEMAILADDRESSES
																   WHERE ROWNUMBER3 = @ACTIVEROW3)
							END
						SET @ACTIVEROW3 = @ACTIVEROW3 + 1
					END
			END
		ELSE 
			SET @ACTIVEROW3 = 1
			BEGIN
				SET @BEFOREEMAIL =         (SELECT phone	
											FROM recipients		
											WHERE row_number  = @ACTIVEROW)
				WHILE @LASTROW3 >= @ACTIVEROW3
					BEGIN
						SET @MAIL = @MAIL + '; ' + @BEFOREEMAIL + (SELECT EMAIL 
																   FROM #TEXTEMAILADDRESSES
																   WHERE ROWNUMBER3 = @ACTIVEROW3)
						SET @ACTIVEROW3 = @ACTIVEROW3 + 1
					END
			END
		SET @ACTIVEROW = @ACTIVEROW + 1
	END

EXEC MSDB.DBO.sp_send_dbmail 
	@PROFILE_NAME = 'atlhoops',
	@RECIPIENTS = @MAIL,
	@BLIND_COPY_RECIPIENTS = @BCCMAIL,
	@SUBJECT = @NEWSUBJECT,
	@BODY = @NEWBODY,
	@BODY_FORMAT = 'HTML';

END
GO


